### ISSUE TITLE
How to run scalastyle automatically on compile?

### ISSUE THREAD

**Issue by velvia** [scalastyle/scalastyle-sbt-plugin#11]
Sorry this is more of a question.   How do I modify my build file so that I can get scalastyle on run on every compile?  I tried this, but it doesn't work:

```
  compile in Compile <<= (compile in Compile) dependsOn(
     org.scalastyle.sbt.Tasks.scalastyle)
```

It throws this:

```
<console>:65: error: type mismatch;
 found   : sbt.Project.Initialize[sbt.InputTask[Unit]]
 required: sbt.Scoped.AnyInitTask
              compile in Compile <<= (compile in Compile) dependsOn(Tasks.scalastyle)
```

I tried to get around this by casting scalastyle task to `sbt.Scoped.AnyInitTask` but this fails with a CastException.

Any other ideas?

**Comment by asarkar** [comment]
SBT noob here, how to make scalastyle run automatically after test (or compile), not the other way round? Syntax shown by @yongjunj doesn't work with SBT 1.x. I understand how to set up task dependencies, but that doesn't make scalastyle run automatically _after_ test.
