### ISSUE TITLE
Add ability to run as part of sbt test

### ISSUE THREAD

**Issue by DomBlack** [scalastyle/scalastyle-sbt-plugin#12]
Is it possible to make this plugin run as part of the `sbt test` run, and if there are any warnings then to make the tests fail?

This would be really useful for managing shared repo's and using a CI to enforce coding style. (Such as travis)

**Comment by matthewfarwell** [comment]
This is now possible using the method defined in 

http://www.scalastyle.org/sbt.html

If it is not, please reopen this issue.
