### ISSUE TITLE
Create a cross build for both 2.11 and 2.10

### ISSUE THREAD

**Issue by jasonchaffee** [scalastyle/scalastyle-sbt-plugin#20]
It would be nice if the plugin would work with both scala versions.  Need to wait for sbt on 2.11.

http://stackoverflow.com/questions/23282469/does-sbt-builds-againts-scala-2-11

**Comment by code-rhino** [comment]
Is there a SBT repository that will work with 2.11?

**Comment by matthewfarwell** [comment]
There should be. What is your problem? Are you having problems - if you are then could provide a small project which doesn't work. Thanks.

**Comment by agenovese** [comment]
Hello, not sure if this is the same issue that code-rhino is referencing, but I am unable to use the scalastyle sbt plugin with a scala 2.11 project. The error is an unresolved dependency. 

The url I would have expected to find the plugin at is https://oss.sonatype.org/content/repositories/releases/org/scalastyle/scalastyle-sbt-plugin_2.11_0.13/0.6.0/scalastyle-sbt-plugin-0.6.0.pom

the test project is just a build.sbt file as follows:

name := "testScalaStyle"

version := "1.0"

scalaVersion := "2.11.1"

resolvers ++= Seq(
  "sonatype-releases" at "https://oss.sonatype.org/content/repositories/releases/"
)


addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.6.0")

**Comment by matthewfarwell** [comment]
You need to put the addSbtPlugin into project/plugins.sbt, not directly in build.sbt.

project/plugins.sbt contains the dependencies of the *build*, whereas build.sbt contains the dependencies of *your code*.
