### ISSUE TITLE
version 0.5 does not generate an output file

### ISSUE THREAD

**Issue by neurolabs** [scalastyle/scalastyle-sbt-plugin#26]
updated from 0.4 to 0.5. Since then, no scalastyle-result.xml-file or any other similar file is written when calling sbt scalastyle.

**Comment by matthewfarwell** [comment]
I'm closing this as fixed

**Comment by neurolabs** [comment]
Sorry, didn't notice your reply from dec '14. Currently on 0.7 and everything is fine.
