### ISSUE TITLE
<0.6.0> rror: object scalastyle is not a member of package org.scalastyle.sbt.PluginKeys.scalastyle.toTask("").value

### ISSUE THREAD

**Issue by xwcheng** [scalastyle/scalastyle-sbt-plugin#32]
I am follow the manual at http://www.scalastyle.org/sbt.html try to make the style check part of test flow.

after I add below to  projects/plugins.sbt

addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.6.0")
resolvers += "sonatype-releases" at "https://oss.sonatype.org/content/repositories/releases/"
// Create a default Scala style task to run with tests
lazy val testScalaStyle = taskKey[Unit]("testScalaStyle")
testScalaStyle := {
  org.scalastyle.sbt.PluginKeys.scalastyle.toTask("").value
}
(test in Test) <<= (test in Test) dependsOn testScalaStyle

I got the error.
---------------------------------
error: object scalastyle is not a member of package org
  org.scalastyle.sbt.PluginKeys.scalastyle.toTask("").value
      ^

**Comment by matthewfarwell** [comment]
Hi,

I've added a bit of a better description.

http://www.scalastyle.org/sbt.html

Have fun,

Matthew Farwell.

2014-12-30 21:51 GMT+01:00 Travis Kaufman <notifications@github.com>:
