### ISSUE TITLE
Need a more customizable way of getting the config file

### ISSUE THREAD

**Issue by le-doude** [scalastyle/scalastyle-sbt-plugin#34]
To sync all our config files for various setups for our devs we use services that require some form of authentication.
For example:
We sometime use private github repos to get a file hosted on a "config" repo. We can get those files with 

`curl -u <some_oauth_token>:x-basic-oauth https://raw.githubusercontent/[user/org]/[reponame]/[branch]/[path_tyo_file]`

It would be nice to have something that allows for more complex requests by setting headers. Or defining our own process.

**Comment by matthewfarwell** [comment]
I'm reluctant to start adding authentication to the scalastyle plugin. Apart from it being a lot of new options (username/password, basic/digest, should we ignore certificate problems, etc. etc.), I don't think it fits. You can always make the scalastyle task dependent upon another task - this would probably give you what you need.

**Comment by le-doude** [comment]
That is what I am doing

    lazy val updateScalaStyle = taskKey[Unit]("updateScalaStyle")
    
    lazy val refreshConfFile: Long = 24 * 60 * 60 * 1000

    updateScalaStyle := {
      val conf = file("scalastyle-config.xml")
      if (!conf.exists() || (new Date().getTime - conf.lastModified()) > refreshConfFile){
        val oauthToken = "<MYTOKEN>"
        val configFileUrl = "https://raw.githubusercontent.com/user/repo/branch/path/scalastyle-config.xml"
        val result: Int = s"curl -u $oauthToken:x-oauth-basic $configFileUrl -O" !
      }else{
        println("No need to update")
      }
    }

    (scalastyle in Compile) <<= (scalastyle in Compile) dependsOn updateScalaStyle

    (scalastyle in Test) <<= (scalastyle in Test) dependsOn updateScalaStyle

I plan on adding a call to the github api to check if it has been updated instead of the 24 hours expiry. But the gist of it is here.

**Comment by matthewfarwell** [comment]
Could you perhaps raise a PR to add this to the docs? If not, I will do it

https://github.com/scalastyle/scalastyle.github.com/blob/master/sbt.markdown

**Comment by 2rs2ts** [comment]
@le-doude Are you using personal access tokens for your solution? It'd be nice to have something that "just works" with enterprise github too.

**Comment by le-doude** [comment]
@2rs2ts 
Here is the final version I am using to get file from a github private repo. It works fine and the speed is quite fast in the scalastyle conf case. I tried comparing `sha` using github API v3 but it was slower (it became 2 calls on update needed) or same speed (when non need to update) at most so I just update the file every single time.
BTW I `.gitignore` the file so that everybody in the project is up to date all the time on the scalastyle rules.

https://gist.github.com/8d17f8355138bea4d7a5.git

@matthewfarwell sure

**Comment by 2rs2ts** [comment]
@le-doude Using `.gitignore` works but if you use the current download option the file gets downloaded to `target/scalastyle-config.xml` and the plugin uses that file instead. When you go to issue a PR for this feature you can have the plugin continue to take advantage of that. Then you will also be able to use the `scalastyleConfigRefreshHours` setting, which I admit isn't as nice as using the github API, but it will work for non-github users!

**Comment by matthewfarwell** [comment]
Tidying the issues list, closing this issue. If this is still a problem, please reopen or raise another issue.
