### ISSUE TITLE
How do I exclude files/folders?

### ISSUE THREAD

**Issue by mthurlin** [scalastyle/scalastyle-sbt-plugin#35]
I would like to exclude some folders/files from being checked, how do I do that?

The command-line version of scalastyle takes the source directory to use, but I can't figure out how to do that with scalastyle-sbt.

**Comment by matthewfarwell** [comment]
By default the sbt plugin uses the normal scalaSource setting. There isn't a way to exclude a particular set of directories at the minute.

**Comment by jeffsteinmetz** [comment]
+1

Does this commit improve this?

https://github.com/scalastyle/scalastyle-sbt-plugin/commit/313833043d734b974869c6d3f7f13d6a56a0b050

**Comment by samarthgupta437** [comment]
+1 would like to see this feature.

**Comment by matthewfarwell** [comment]
This should be fixed. You can now supply a list of files to scalastyleSources. This should be available to test in 0.9.0-SNAPSHOT. Closing issue.

**Comment by anancds** [comment]
if use play framework，you can try this:

```
lazy val root = (project in file(".")).enablePlugins(PlayScala).
  settings(
    (scalastyleSources in Compile) := {
      val scalaSourceFiles = ((scalaSource in Compile).value ** "*.scala").get
      scalaSourceFiles.filterNot(_.getAbsolutePath.contains("example.scala")).filterNot(_.getAbsolutePath.contains("somefolder"))
    }
  )
```

**Comment by arthurarty** [comment]
> if use play framework，you can try this:
> 
> ```
> lazy val root = (project in file(".")).enablePlugins(PlayScala).
>   settings(
>     (scalastyleSources in Compile) := {
>       val scalaSourceFiles = ((scalaSource in Compile).value ** "*.scala").get
>       scalaSourceFiles.filterNot(_.getAbsolutePath.contains("example.scala")).filterNot(_.getAbsolutePath.contains("somefolder"))
>     }
>   )
> ```

When using the above you code in your `build.sbt` might run into the error.
```
warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash
```
Updated way to do it is.
```
  (Compile / scalastyleSources) := {
    val scalaSourceFiles = ((Compile / scalaSource).value ** "*.scala").get
    scalaSourceFiles.filterNot(_.getAbsolutePath.contains("example.scala")).filterNot(_.getAbsolutePath.contains("somefolder"))
  },
```
[Reference](https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash)
### Note:
This worked with the `sbt plugin`.
