### ISSUE TITLE
Incompatible with AutoPlugin

### ISSUE THREAD

**Issue by brunon** [scalastyle/scalastyle-sbt-plugin#48]
ScalaStyle plugin uses the legacy `sbt.Plugin` class which is not compatible with the newer `AutoPlugin` mechanism.

In particular, I'm writing an `AutoPlugin` that modifies the `scalastyle` task to add automatic "fail on warnings" by applying the "w" argument using `partialInput`. That works well if the override to `scalastyle` task is specified in a project's `build.sbt` file, but if it's specified in an `AutoPlugin` then the override order is not respected: the task definition present in your plugin overrides anything I specify in my AutoPlugin

It would be good to migrate your code to use `sbt.AutoPlugin` instead

**Comment by matthewfarwell** [comment]
Fixed by #52.
