### ISSUE TITLE
plugins.sbt in IntelliJ IDEA - plugin not found

### ISSUE THREAD

**Issue by lopezavila85** [scalastyle/scalastyle-sbt-plugin#51]
Hello,

I am following the instructions in [Scalastyle](http://www.scalastyle.org/sbt.html) in order to add the plugin into my Scala project. I have added "addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")" into a new plugins.sbt file.

However, when I refresh my project in IntelliJ IDEA, I get the following error:

Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[...]
[error](*:update) sbt.ResolveException: unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
[error](*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
[error] Total time: 1 s, completed 12-jun-2016 14:46:45

What am I doing wrong? The project is using Scala 2.11.7 and SBT 0.13.9

**Comment by matthewfarwell** [comment]
scalastyle is in the OSS Sonatype repo. You will probably need to add the sonatype repo into your configuration for Intellij - see http://www.scalastyle.org/sbt.html. However, I don't know how to do this for Intellij.

**Comment by matthewfarwell** [comment]
Closing, presumed fixed. If there is still a problem, please reopen or raise a new issue.
