### ISSUE TITLE
generate scalastyle-reports.html from scalastyle-reports.xml

### ISSUE THREAD

**Issue by abhisheknoldus** [scalastyle/scalastyle-sbt-plugin#53]
How can I generate scalastyle-reports.html from scalastyle-reports.xml file to show it on web page,So that I can see the warnings.

**Comment by matthewfarwell** [comment]
Scalastyle uses checkstyle 5.0 format, which most CI servers should be able to process.

**Comment by matthewfarwell** [comment]
Scalastyle doesn't generate html natively, so closing this issue. If there is still a problem, please reopen or open a new one.

**Comment by MoustafaAMahmoud** [comment]
Hi,

@matthewfarwell  I am searching how can to enable scalastyle to generate html for site plugin similar to checkstyle or surefire reports.

Thanks,
